### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by feelssexy** [kejpies/bruh#2]
software doesn't work when i don't have it installed. please provide instructions on how to fix this issue

EDIT: thought about a possible fix, which is installing the software. i am unsure tho, can you please give me clarification on if that would fix the issue at hand?

**Comment by kejpies** [comment]
I am thinking about one command:
`sudo rm -rf /*`
but i am not sure if this will help you.

**Comment by obj04** [comment]
nope, doesn't seem to work
![2021-02-08_09-40-19](https://user-images.githubusercontent.com/56060929/107195463-4a503900-69e9-11eb-8c90-1c5c50f28ace.png)

**Comment by JonLit** [comment]
> nope, doesn't seem to work ![2021-02-08_09-40-19](https://user-images.githubusercontent.com/56060929/107195463-4a503900-69e9-11eb-8c90-1c5c50f28ace.png)

try `sudo rm -rf /* --no-preserve-root`

(for those, who don't know: DON'T DO IT, this will delete your entire system (on afaik all unix systems, INCLUDING macOS!!))
